#yaml extension with anchor for reuse
x-env-file: &env
  - .env

secrets:
  wp-admin_password:
    file: ../secrets/wp-admin_password.txt
  wp-usr_password:
    file: ../secrets/wp-usr_password.txt
  wp-db_password:
    file: ../secrets/wp-db_password.txt
  wp-db-usr_password:
    file: ../secrets/wp-db-usr_password.txt
  mysql_root_password:
    file: ../secrets/mysql_root_password.txt
  ssl-cert:
    file: ../secrets/public_certificate.crt
  ssl-key:
    file: ../secrets/private.key

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bposa/data/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bposa/data/wordpress

networks:
  network:
    name: docker-network
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:${MARIADB_VERSION}
    restart: unless-stopped
    env_file: *env
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u \"$$WORDPRESS_DATABASE_USER\" --password=\"$$(cat /run/secrets/wp-db-usr_password)\" "]
      interval: 10s
      timeout: 10s
      retries: 15
    secrets:
      - mysql_root_password
      - wp-db-usr_password

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:local
    restart: unless-stopped
    env_file: *env
    networks:
      - network
    expose:
      - 9000
    volumes:
      - wordpress:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f php-fpm83 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - wp-admin_password
      - wp-usr_password
      - wp-db-usr_password

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:${NGINX_VERSION}
    restart: unless-stopped
    env_file: *env
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - network
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./requirements/static-site:/var/www/static-site
      - ../secrets/public_certificate.crt:/etc/nginx/ssl/public_certificate.crt:ro
      - ../secrets/private.key:/etc/nginx/ssl/private.key:ro
    secrets:
      - ssl-cert
      - ssl-key

  static:
    container_name: static
    build: ./requirements/static-site
    image: static:0.1
    restart: unless-stopped
    env_file: *env
    networks:
      - network